// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecondTask.Data;

#nullable disable

namespace SecondTask.Migrations
{
    [DbContext(typeof(SecondDbContext))]
    [Migration("20220530153433_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SecondTask.Data.EsplEmployee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EmployeeAge = 20,
                            EmployeeID = 101,
                            EmployeeName = "Hi-Tech"
                        },
                        new
                        {
                            ID = 2,
                            EmployeeAge = 20,
                            EmployeeID = 2,
                            EmployeeName = "Hi-Tech"
                        },
                        new
                        {
                            ID = 3,
                            EmployeeAge = 20,
                            EmployeeID = 3,
                            EmployeeName = "Hi-Tech"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
